### ISSUE TITLE
Searching with "e" as first word kills the window.

### ISSUE THREAD

**Issue by ashraddhansh** [savedra1/clipse#118]
After pressing "/" for search the clipboard when I search something that starts with word "e" the window get killed.

**Comment by savedra1** [comment]
Hi @ashraddhansh 👋 

I think this is due to the fuzzy finder not being able to read a certain character in one of your clipboard entries. 

I would recommend pinning any items you don't want to lose, run `clipse -clear` and see if you still have the issue. If you have any pinned items that are non-standard characters, try removing those also. 

If that doesn't fix it, please run the `clipse` command directly in the terminal and reproduce the error so you can get the debug trace. There may also be a meaningful error added to your `clipse.log` file. 

Let me know if the above helps!

**Comment by ashraddhansh** [comment]
Thanks, clearing the clipboard solved my issue.

**Comment by savedra1** [comment]
Glad to hear it! 

It would still be good for this exception to be caught, so I will investigate a way to handle/avoid it and update the FAQ in the meantime. 

Thanks
