### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by sentakuhm** [savedra1/clipse#33]
it not always, just sometimes cpu is high

![swappy-20240424-091540](https://github.com/savedra1/clipse/assets/25133437/4ad6cd7e-f9bb-4050-aa09-da0b152be721)

**Comment by savedra1** [comment]
Hi @sentakuhm 👋

Thank you for raising this. I have not seen it get anywhere near to that % before!

I will investigate this as part of the next release. To help me, could you please let me know the following:

- what content type was being copied to your clipboard when the usage was showing this high? E.g image data/mp4 etc...
- what is your terminal environment and OS in use? Would also be good to understand which system clipboard app you are using (xclip/wl-clipboard/something else) 
- did any other process spike at the same time as `clipse --listen-shell` or was it only this process? 

Thanks!

**Comment by sentakuhm** [comment]
OS: Arch linux.
Terminal: Kitty.
WM: Hyprland.
Clipboard: wl-clipboard.

Settings on hypr:
```
exec-once = wl-clipboard-history -t
exec-once = clipse -listen
bind = SUPER, V, exec,  kitty --class floating -e zsh  -c 'clipse $PPID'
```
as i said its not always happen, but i think it happen on copying media files images/videos.
and no, no other other process spike at the same time only clipse.

**Comment by sentakuhm** [comment]
I record what happened when i take screenshot:

https://github.com/savedra1/clipse/assets/25133437/0a319103-4a63-4e79-bb13-efc67760fb51

**Comment by savedra1** [comment]
@sentakuhm thank you!

Looks like this is mainly gonna be down to the content type being copied (media data specifically).

_I think_ I have a fix so gonna work on that as part of the next release. Will keep you updated 😄

**Comment by savedra1** [comment]
@sentakuhm I've published a new release that should have sorted this out a bit, haven't got the new Nix/Aur package sorted yet but lmk if you get this working in the meantime if it's helped at all :)

**Comment by sentakuhm** [comment]
@savedra1 i'll check it out, and i use [wf-recorder](https://github.com/ammen99/wf-recorder) for desktop record.

**Comment by savedra1** [comment]
Thank you @sentakuhm 🙏 been looking for a good one. let me know how it goes

**Comment by savedra1** [comment]
@sentakuhm have just seen your edit! 

Am very surprised to hear this as the change I made included significantly reducing the rate at which the app would check your clipboard contents when media data is held. The only thing I can think of that would _increase_ the cpu usage is the updates to the UI used for this release but that should not apply here and would be super minimal. 

As you built this from source, are you 100% sure the previous version is not the one that's running the listener still? Eg if you still have the previous installed, running `clipse -listen` maybe be using that still. I'd recommend using `./<new clipe binary> --listen shell`. 

The new [AUR package](https://aur.archlinux.org/packages/clipse) should also be good to go now btw, maybe installing from there would help. 

If it is the new version I'll need to have a deeper think about this as it's possibly caused by the way it interacts with your hyprland/shell envs.  

Lmk! 

Thanks :pray:

**Comment by sentakuhm** [comment]
Yes, first i completely removed the old version and build from the source, second i remove built one then installed from AUR, checking with `clipse -v` the output is: `clipse v0.0.7`, but both gave same issue.

to be sure this is my settings:
```
exec-once = wl-clipboard-history -t
exec-once = clipse -listen  # run listener on startup
bind = SUPER, V, exec,[float;size 450 590]  kitty --class floating -e zsh  -c 'clipse' # [float;size 450 590] is just custom window size.
```

**Comment by savedra1** [comment]
Thanks for confirming @sentakuhm. Yeah I use `wl-clipboard`. 

I see you're also running the `wl-clipboard-history` script on startup, this shouldn't directly affect the behaviour of clipse but as they would both be interacting with the system clipboard simultaneously I wonder if this is causing any complications. 

I would suggest stopping the `wl-clipboard-history` script to see if that makes any difference. Alternatively you could not run the `clipse-listen` and update the wrapper around `wl-clipboard` so that it updates the history file instead, though that would require a lot more engineering effort. Will try and replicate this myself also.

Planning to cross-compile some `c` for a more event-based clipboard listener, was reluctant to use an extra dependency for this `wl-clipboard` but may look into making that a temporary option

**Comment by savedra1** [comment]
https://github.com/savedra1/clipse/assets/99875823/7d87ecc4-e64b-4ad8-8567-c4702f48884b

This is my htop when copying a large image file on the new release (2% CPU). What machine specs are you running? wondering if that could be making a difference also

**Comment by sentakuhm** [comment]
stopping the `wl-clipboard-history` script no helping.

is there any option to debug?

**Comment by savedra1** [comment]
I see :thinking: debugging in clipse is still limited to error messages. When `clipse -listen` is ran it executes the command `nohup clipse --listen-shell >/dev/null 2>&1 &` which discards all logs, but you could recreate this, getting it to point to a log file instead with `nohup clipse --listen-shell >> /path/to/logfile.log 2>&1 &` and see if that shows you anything helpful.

You could also edit the source code to add print statements if you already have an idea of what you'd be looking for here. In that case you could simply run `clipse --listen-shell` and see what gets printed to the terminal while the process runs.  
 
I haven't been able to recreate this also so still wondering if it could be hardware related. Will see what debugging logs I can find though and let you know if I spot a way to find some clues.

**Comment by sentakuhm** [comment]
on log file there is no thing except `nohup: ignoring input`.

**Comment by savedra1** [comment]
Thank you for checking @sentakuhm. Looks like I would need to implement some better, system-level debugging here for that to show any info. I'm sorry we haven't got very far with this, I'm not sure of the cause still but you could try the following:

- use a tool like `strace`/`perf` to inspect the PID of the running listener process. EG `strace -p <PID>`
- clear the file contents that are being loaded into the TUI with `clipse -clear' _(this will remove all clipboard histiry data and temp files used)_ it's **possible there is a certain file that the program is having difficulty parsing**
- run `ps aux | grep clipse` to ensure only a single clipse process is running _(something might be going wrong when terminating an existing listener)_ `clipse -kill` can then be used to kill all sessions
- run `clipse --listen-shell` directly in a terminal without the `nohup` process to see if this helps (maybe nohup is causing some system issue) 

These are the only things that come to mind for ways in which clipse is interacting with your system. If none produce any positive results will need to think about other ways to analyse what's going on under the hood when the binary runs on your system. 

Your perseverance is much appriciated, let me know how it goes! :smile:

**Comment by sentakuhm** [comment]
OMG!! what a relief, `clipse -clear` solved my issue, even after rebooting and try again cpu was only 2%. thank you!!!.

**Comment by savedra1** [comment]
Amazing! Must've been some unexpected binary data pattern from a certain file. 

Will keep this in mind and add to the FAQs. 

Thanks again for sticking with it and for using clipse 🫡

**Comment by ArtemChandragupta** [comment]
I also get this on NixOS unstable + Hyprland... clipse eat more cpu than firefox. 
![image](https://github.com/savedra1/clipse/assets/90765302/7ca43fdb-b749-4e19-89d3-3ce9f06055c9)

**Comment by savedra1** [comment]
Hi @ArtemChandragupta,

Have you tried the above fix? should be due to the bin data from a certain image file causing parse issues. Will be looking into this more for the next release.

**Comment by ArtemChandragupta** [comment]
Is the fix is just to do clipse --clear to remove all clipboard history? Can I just remove image files by 'x' keybind?

This is not truly 0,5%, btop is weird. It actually more like 4%, because now it uses 7% of cpu while before it used something like  3% in same situation. And it is important, because I notified that by temperature increase.

**Comment by ArtemChandragupta** [comment]
This is without cliphist, same tabs are open in firefox. Completely different cpu usage graph 
![image](https://github.com/savedra1/clipse/assets/90765302/a5b8e332-c246-4c0f-9631-bbc39f3e2cda)

**Comment by savedra1** [comment]
Gotcha @ArtemChandragupta 

You shouldn't need to clear everything, likely just a particular image file causing the increased usage so you can try deleting individual files using `x`, I guess that takes longer. 

Planning to implement more specific clear commands in the future, to specifically clear all images/non-pinned items etc. This is all I can suggest for now though. It's on my radar as something to look into more, let me know if you still get higher than expected usage after removing your images though.

**Comment by ArtemChandragupta** [comment]
Issue is still here after clearing the buffer...
![image](https://github.com/savedra1/clipse/assets/90765302/15f75f65-5ec6-4354-8682-4db21e7e866c)

**Comment by ArtemChandragupta** [comment]
Congratulations! Now (maybe with 1.0.7 patches, while I am on 1.0.9) CPU usage is good on my machine.

**Comment by savedra1** [comment]
thank you @ArtemChandragupta!
