### ISSUE TITLE
[Feature Request] persistent words

### ISSUE THREAD

**Issue by gars-cmd** [savedra1/clipse#43]
Is it possible to configure in the config.json persistent words that you want to keep in the clipboard manager?

**Comment by savedra1** [comment]
Hi @gars-cmd :wave: 

Thanks for raising this. To make sure I understand, what would the value of this be, given there is an existing pinned items feature? Maybe so that you wouldn't need to worry about pinning them? 

The cmd `clipse -clear` currently removes all items including pined items from the history, but I'm planning to updat ethis so that pinned items would remain and _have_ to be deleted within the TUI or implement a new cmd like `clipse --clear-all`.  

Would that meet your requirement here?

**Comment by gars-cmd** [comment]
Sorry but I think I missed the pinned items in the doc.
Otherwise, the idea of -clear (not included pinned items)  and --clear-all (pinned items) seems to me to be a good solution.
thank you .
